airbase:
  description: WebProjectBasic Space Station
  version: v1.0
  initdatabase-enable: false
  recorddborm-enable: true
  esserver-enable: false
spring:
  datasource:
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.dbport}/${spring.datasource.dbname}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    user: root
    password: 1234
    driverclassname: com.mysql.cj.jdbc.Driver
    dbtype: mysql
    dbname: airbaseerror
    dbport: 3306
    host: 127.0.0.1
    dbconfigfile: mysql-dbconfig.json
  elasticsearch:
    host: 127.0.0.1
    port: 9500
    tcpport: 9300
    user: elastic
    password: 123ABCdef*
    scheme: http