spring:
  datasource:
    host: 127.0.0.1
    dbport: 3306
    user: root
    password: 1234
    driverclassname: com.mysql.cj.jdbc.Driver
    dbtype: mysql
    dbname: airbaseerror
    dbconfigfile: mysql-dbconfig.json
  elasticsearch:
    host: 127.0.0.1
    port: 9500
    tcpport: 9300
    user: elastic
    password: 123ABCdef*
    scheme: http
airbase:
  description: WebProjectBasic Space Station
  version: v1.0
  initdatabase-enable: true
  recorddborm-enable: false
  apilog-enable: true
  esserver-enable: false
  esserver-lognotes: true